# Generated by Django 5.1.2 on 2024-11-02 18:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField(max_length=70)),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(max_length=80)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=120)),
                ('bg_img', models.ImageField(upload_to='slides/')),
                ('order', models.IntegerField(help_text='Order of the sliding image section.', unique=True)),
            ],
        ),
    ]
