# Generated by Django 5.1.2 on 2024-11-02 18:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=250),
        ),
    ]
