# Generated by Django 5.1.2 on 2024-11-02 19:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Genz', '0002_alter_homeslider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='subtitle',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
