# Generated by Django 5.1.2 on 2024-11-07 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genz', '0004_category_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='socialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'linkedin'), ('twitter', 'twitter'), ('facebook', 'facebook'), ('instagram', 'instagram'), ('pinterest', 'pinterest'), ('youtube', 'youtube')], max_length=20)),
                ('link', models.URLField(validators=[django.core.validators.URLValidator(message='Enter a valid URL.')])),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='Genz.mentor')),
            ],
        ),
    ]
